#!/usr/bin/env bash

function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" >/dev/null 2>&1
}

echo 'Checking for changes in bun.lock...'

if changed 'bun.lock'; then
  echo "📦 bun.lock changed. Run bun install to bring your dependencies up to date."

  yarn
fi

echo 'You are up to date :)'
echo 'If necessary, you can generate again the native code.'

exit 0
